// Proto definitions for Hudl view data types.
// Generated from template proto blocks.
//
// To regenerate Go bindings:
//   protoc --go_out=. --go_opt=paths=source_relative proto/views.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/views.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionStatus represents the status of a transaction.
type TransactionStatus int32

const (
	TransactionStatus_STATUS_UNKNOWN TransactionStatus = 0
	TransactionStatus_STATUS_ACTIVE  TransactionStatus = 1
	TransactionStatus_STATUS_PENDING TransactionStatus = 2
	TransactionStatus_STATUS_FAILED  TransactionStatus = 3
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_ACTIVE",
		2: "STATUS_PENDING",
		3: "STATUS_FAILED",
	}
	TransactionStatus_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"STATUS_ACTIVE":  1,
		"STATUS_PENDING": 2,
		"STATUS_FAILED":  3,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_views_proto_enumTypes[0].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_proto_views_proto_enumTypes[0]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_views_proto_rawDescGZIP(), []int{0}
}

// SimpleData is the data type for the Simple view.
type SimpleData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Features      []string               `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleData) Reset() {
	*x = SimpleData{}
	mi := &file_proto_views_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleData) ProtoMessage() {}

func (x *SimpleData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_views_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleData.ProtoReflect.Descriptor instead.
func (*SimpleData) Descriptor() ([]byte, []int) {
	return file_proto_views_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SimpleData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SimpleData) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

// LayoutData is the data type for the AppLayout view.
type LayoutData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	IsLoggedIn    bool                   `protobuf:"varint,3,opt,name=is_logged_in,json=isLoggedIn,proto3" json:"is_logged_in,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"` // Pre-rendered HTML from child component
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayoutData) Reset() {
	*x = LayoutData{}
	mi := &file_proto_views_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayoutData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutData) ProtoMessage() {}

func (x *LayoutData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_views_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutData.ProtoReflect.Descriptor instead.
func (*LayoutData) Descriptor() ([]byte, []int) {
	return file_proto_views_proto_rawDescGZIP(), []int{1}
}

func (x *LayoutData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LayoutData) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LayoutData) GetIsLoggedIn() bool {
	if x != nil {
		return x.IsLoggedIn
	}
	return false
}

func (x *LayoutData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// RegistrationFormData is the data type for the RegistrationForm view.
type RegistrationFormData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	TermsAccepted bool                   `protobuf:"varint,3,opt,name=terms_accepted,json=termsAccepted,proto3" json:"terms_accepted,omitempty"`
	CsrfToken     string                 `protobuf:"bytes,4,opt,name=csrf_token,json=csrfToken,proto3" json:"csrf_token,omitempty"`
	UsernameError string                 `protobuf:"bytes,5,opt,name=username_error,json=usernameError,proto3" json:"username_error,omitempty"`
	EmailError    string                 `protobuf:"bytes,6,opt,name=email_error,json=emailError,proto3" json:"email_error,omitempty"`
	PasswordError string                 `protobuf:"bytes,7,opt,name=password_error,json=passwordError,proto3" json:"password_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationFormData) Reset() {
	*x = RegistrationFormData{}
	mi := &file_proto_views_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationFormData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationFormData) ProtoMessage() {}

func (x *RegistrationFormData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_views_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationFormData.ProtoReflect.Descriptor instead.
func (*RegistrationFormData) Descriptor() ([]byte, []int) {
	return file_proto_views_proto_rawDescGZIP(), []int{2}
}

func (x *RegistrationFormData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegistrationFormData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegistrationFormData) GetTermsAccepted() bool {
	if x != nil {
		return x.TermsAccepted
	}
	return false
}

func (x *RegistrationFormData) GetCsrfToken() string {
	if x != nil {
		return x.CsrfToken
	}
	return ""
}

func (x *RegistrationFormData) GetUsernameError() string {
	if x != nil {
		return x.UsernameError
	}
	return ""
}

func (x *RegistrationFormData) GetEmailError() string {
	if x != nil {
		return x.EmailError
	}
	return ""
}

func (x *RegistrationFormData) GetPasswordError() string {
	if x != nil {
		return x.PasswordError
	}
	return ""
}

// Feature represents a single feature item.
type Feature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Icon          string                 `protobuf:"bytes,1,opt,name=icon,proto3" json:"icon,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	LinkUrl       string                 `protobuf:"bytes,4,opt,name=link_url,json=linkUrl,proto3" json:"link_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feature) Reset() {
	*x = Feature{}
	mi := &file_proto_views_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_views_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_proto_views_proto_rawDescGZIP(), []int{3}
}

func (x *Feature) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Feature) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Feature) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Feature) GetLinkUrl() string {
	if x != nil {
		return x.LinkUrl
	}
	return ""
}

// FeatureListData is the data type for the FeatureList view.
type FeatureListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      []*Feature             `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureListData) Reset() {
	*x = FeatureListData{}
	mi := &file_proto_views_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureListData) ProtoMessage() {}

func (x *FeatureListData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_views_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureListData.ProtoReflect.Descriptor instead.
func (*FeatureListData) Descriptor() ([]byte, []int) {
	return file_proto_views_proto_rawDescGZIP(), []int{4}
}

func (x *FeatureListData) GetFeatures() []*Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

// Transaction represents a single transaction.
type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerName    string                 `protobuf:"bytes,2,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomerEmail   string                 `protobuf:"bytes,3,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	AmountFormatted string                 `protobuf:"bytes,4,opt,name=amount_formatted,json=amountFormatted,proto3" json:"amount_formatted,omitempty"`
	Status          TransactionStatus      `protobuf:"varint,5,opt,name=status,proto3,enum=hudl.TransactionStatus" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_views_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_views_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_views_proto_rawDescGZIP(), []int{5}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *Transaction) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

func (x *Transaction) GetAmountFormatted() string {
	if x != nil {
		return x.AmountFormatted
	}
	return ""
}

func (x *Transaction) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_STATUS_UNKNOWN
}

// DashboardData is the data type for the Dashboard view.
type DashboardData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RevenueFormatted string                 `protobuf:"bytes,1,opt,name=revenue_formatted,json=revenueFormatted,proto3" json:"revenue_formatted,omitempty"`
	ActiveUsers      int32                  `protobuf:"varint,2,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	SystemLoad       int32                  `protobuf:"varint,3,opt,name=system_load,json=systemLoad,proto3" json:"system_load,omitempty"`
	Transactions     []*Transaction         `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DashboardData) Reset() {
	*x = DashboardData{}
	mi := &file_proto_views_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardData) ProtoMessage() {}

func (x *DashboardData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_views_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardData.ProtoReflect.Descriptor instead.
func (*DashboardData) Descriptor() ([]byte, []int) {
	return file_proto_views_proto_rawDescGZIP(), []int{6}
}

func (x *DashboardData) GetRevenueFormatted() string {
	if x != nil {
		return x.RevenueFormatted
	}
	return ""
}

func (x *DashboardData) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *DashboardData) GetSystemLoad() int32 {
	if x != nil {
		return x.SystemLoad
	}
	return 0
}

func (x *DashboardData) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// ButtonData is the data type for the StyledButton view.
type ButtonData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Disabled      bool                   `protobuf:"varint,2,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ButtonData) Reset() {
	*x = ButtonData{}
	mi := &file_proto_views_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ButtonData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonData) ProtoMessage() {}

func (x *ButtonData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_views_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonData.ProtoReflect.Descriptor instead.
func (*ButtonData) Descriptor() ([]byte, []int) {
	return file_proto_views_proto_rawDescGZIP(), []int{7}
}

func (x *ButtonData) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ButtonData) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

var File_proto_views_proto protoreflect.FileDescriptor

const file_proto_views_proto_rawDesc = "" +
	"\n" +
	"\x11proto/views.proto\x12\x04hudl\"`\n" +
	"\n" +
	"SimpleData\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeatures\"{\n" +
	"\n" +
	"LayoutData\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12 \n" +
	"\fis_logged_in\x18\x03 \x01(\bR\n" +
	"isLoggedIn\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"\xfd\x01\n" +
	"\x14RegistrationFormData\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12%\n" +
	"\x0eterms_accepted\x18\x03 \x01(\bR\rtermsAccepted\x12\x1d\n" +
	"\n" +
	"csrf_token\x18\x04 \x01(\tR\tcsrfToken\x12%\n" +
	"\x0eusername_error\x18\x05 \x01(\tR\rusernameError\x12\x1f\n" +
	"\vemail_error\x18\x06 \x01(\tR\n" +
	"emailError\x12%\n" +
	"\x0epassword_error\x18\a \x01(\tR\rpasswordError\"p\n" +
	"\aFeature\x12\x12\n" +
	"\x04icon\x18\x01 \x01(\tR\x04icon\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\blink_url\x18\x04 \x01(\tR\alinkUrl\"<\n" +
	"\x0fFeatureListData\x12)\n" +
	"\bfeatures\x18\x01 \x03(\v2\r.hudl.FeatureR\bfeatures\"\xc5\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcustomer_name\x18\x02 \x01(\tR\fcustomerName\x12%\n" +
	"\x0ecustomer_email\x18\x03 \x01(\tR\rcustomerEmail\x12)\n" +
	"\x10amount_formatted\x18\x04 \x01(\tR\x0famountFormatted\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.hudl.TransactionStatusR\x06status\"\xb7\x01\n" +
	"\rDashboardData\x12+\n" +
	"\x11revenue_formatted\x18\x01 \x01(\tR\x10revenueFormatted\x12!\n" +
	"\factive_users\x18\x02 \x01(\x05R\vactiveUsers\x12\x1f\n" +
	"\vsystem_load\x18\x03 \x01(\x05R\n" +
	"systemLoad\x125\n" +
	"\ftransactions\x18\x04 \x03(\v2\x11.hudl.TransactionR\ftransactions\">\n" +
	"\n" +
	"ButtonData\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1a\n" +
	"\bdisabled\x18\x02 \x01(\bR\bdisabled*a\n" +
	"\x11TransactionStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x02\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x03B!Z\x1fgithub.com/njr/hudl/pkg/hudl/pbb\x06proto3"

var (
	file_proto_views_proto_rawDescOnce sync.Once
	file_proto_views_proto_rawDescData []byte
)

func file_proto_views_proto_rawDescGZIP() []byte {
	file_proto_views_proto_rawDescOnce.Do(func() {
		file_proto_views_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_views_proto_rawDesc), len(file_proto_views_proto_rawDesc)))
	})
	return file_proto_views_proto_rawDescData
}

var file_proto_views_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_views_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_views_proto_goTypes = []any{
	(TransactionStatus)(0),       // 0: hudl.TransactionStatus
	(*SimpleData)(nil),           // 1: hudl.SimpleData
	(*LayoutData)(nil),           // 2: hudl.LayoutData
	(*RegistrationFormData)(nil), // 3: hudl.RegistrationFormData
	(*Feature)(nil),              // 4: hudl.Feature
	(*FeatureListData)(nil),      // 5: hudl.FeatureListData
	(*Transaction)(nil),          // 6: hudl.Transaction
	(*DashboardData)(nil),        // 7: hudl.DashboardData
	(*ButtonData)(nil),           // 8: hudl.ButtonData
}
var file_proto_views_proto_depIdxs = []int32{
	4, // 0: hudl.FeatureListData.features:type_name -> hudl.Feature
	0, // 1: hudl.Transaction.status:type_name -> hudl.TransactionStatus
	6, // 2: hudl.DashboardData.transactions:type_name -> hudl.Transaction
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_views_proto_init() }
func file_proto_views_proto_init() {
	if File_proto_views_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_views_proto_rawDesc), len(file_proto_views_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_views_proto_goTypes,
		DependencyIndexes: file_proto_views_proto_depIdxs,
		EnumInfos:         file_proto_views_proto_enumTypes,
		MessageInfos:      file_proto_views_proto_msgTypes,
	}.Build()
	File_proto_views_proto = out.File
	file_proto_views_proto_goTypes = nil
	file_proto_views_proto_depIdxs = nil
}
